services:
  registry:
    image: registry:2.8.3
    container_name: registry
    restart: unless-stopped
    ports:
      - "5000:5000" 
    volumes:
      - ./registry-data:/var/lib/registry  
    networks:
      - monitoring_network 

networks:
  monitoring_network:
    external: true  # Use the pre-created network