services:
  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: nginx-certbot
    restart: unless-stopped
    env_file:
      - ./nginx-conf/nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:                                            # Storage can be either a:
      - certs:/etc/letsencrypt                             # Docker managed volume (see list at the bottom)
      - ./nginx-conf/user_conf.d:/etc/nginx/user_conf.d    # or a host mount with a relative or full path.
      - ./nginx-static:/usr/share/nginx/html
    networks:
      - monitoring_network
      - auth_network


volumes:
  certs:

networks:
  monitoring_network:
    external: true  # Use the pre-created network
  auth_network:
    name: auth_network
  
